### ISSUE TITLE
Abspeichern des Modells als .onnx-Datei

### ISSUE THREAD

**Issue by KonstantinRamthun** [PG642/multi-sample-factory#5]
Das gelernte Modell soll nach dem Training als .onnx Datei im train_dir gespeichert werden.

**Comment by KonstantinRamthun** [comment]
### Fehlermeldung beim Exportieren

python multi_sample_factory/algorithms/utils/export_onnx.py --algo=APPO --env=rocket_league_saving_training_single --experiment=example_rocket_league_saving_training_single --train_dir=/work/smkoramt/traindir --device=cpu


[2021-06-14 18:56:34,411][75406] Default env families supported: ['doom_*', 'atari_*', 'dmlab_*', 'mujoco_*', 'MiniGrid*']
[2021-06-14 18:56:34,412][75406] Env registry entry created: rocket_league_
[2021-06-14 18:56:34,558][75406] Loading existing experiment configuration from /work/smkoramt/traindir/example_rocket_league_saving_training_single/cfg.json
[2021-06-14 18:56:34,559][75406] Overriding arg 'device' with value 'cpu' passed from command line
[2021-06-14 18:56:34,559][75406] Adding new argument 'fps'=0 that is not in the saved config file!
[2021-06-14 18:56:34,559][75406] Adding new argument 'render_action_repeat'=None that is not in the saved config file!
[2021-06-14 18:56:34,559][75406] Adding new argument 'no_render'=False that is not in the saved config file!
[2021-06-14 18:56:34,560][75406] Adding new argument 'policy_index'=0 that is not in the saved config file!
[2021-06-14 18:56:34,560][75406] Adding new argument 'record_to'='/work/smkoramt/17228463/multi-sample-factory/../recs' that is not in the saved config file!
[2021-06-14 18:56:34,560][75406] Adding new argument 'continuous_actions_sample'=True that is not in the saved config file!
[INFO] Connected to Unity environment with package version 2.0.0-pre.3 and communication version 1.5.0
[INFO] Connected new brain: GoalKeeping?team=0
[WARNING] The environment contains multiple observations. You must define allow_multiple_obs=True to receive them all. Otherwise, only the first visual observation (or vector observation ifthere are no visual observations) will be provided in the observation.
/work/smkoramt/anaconda3/envs/multi-sample-factory/lib/python3.9/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
[2021-06-14 18:56:36,552][75406] Loading state from checkpoint /work/smkoramt/traindir/example_rocket_league_saving_training_single/checkpoint_p0/checkpoint_000000148_75776.pth...
/work/smkoramt/17228463/multi-sample-factory/multi_sample_factory/algorithms/utils/action_distributions.py:50: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert calc_num_logits(action_space) == raw_logits.shape[-1]
Traceback (most recent call last):
  File "/work/smkoramt/17228463/multi-sample-factory/multi_sample_factory/algorithms/utils/export_onnx.py", line 70, in <module>
    sys.exit(main())
  File "/work/smkoramt/17228463/multi-sample-factory/multi_sample_factory/algorithms/utils/export_onnx.py", line 52, in main
    torch.onnx.export(actor_critic,
  File "/work/smkoramt/anaconda3/envs/multi-sample-factory/lib/python3.9/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/work/smkoramt/anaconda3/envs/multi-sample-factory/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/work/smkoramt/anaconda3/envs/multi-sample-factory/lib/python3.9/site-packages/torch/onnx/utils.py", line 709, in _export
    proto, export_map = graph._export_onnx(
RuntimeError: !node->kind().is_aten() && !node->kind().is_prim() && !node->kind().is_attr() INTERNAL ASSERT FAILED at "../torch/csrc/jit/serialization/export.cpp":500, please report a bug to PyTorch.

**Comment by KonstantinRamthun** [comment]
Also ein Modell für CartPole-V1 konnte ich ganz normal exportieren. Habe dabei die Parameter beim Trainieren genau gleich gehabt. Aber für RoboLeague geht es irgendwie nicht.

**Comment by KonstantinRamthun** [comment]
Also da der einzige Unterschied die Umgebung ist, wäre eine Idee einen eigenen Unity-To-Gym Wrapper zu schreiben, welcher kein Numpy verwendet, da in der [torch.onnx Dokumentation](conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) von Numpy abgeraten wird.
